[general]
max-cmd-history = 100
max-undo = 100
plugins = []

[normal]
primary = "hex"
offset-style = "hex"

[split]
primary = "hex"
secondary = "utf8"
offset-style = "hex"

[diff]
primary = "hex"
secondary = "hex"
offset-style = "hex"

[normal.bin]
column-count = 8
column-size = 1

[normal.hex]
column-count = 32
column-size = 1

[normal.utf8]
column-count = 1
column-size = 64

[split.bin]
column-count = 4
column-size = 1

[split.hex]
column-count = 4
column-size = 4

[split.utf8]
column-count = 8
column-size = 4

[diff.bin]
column-count = 4
column-size = 1

[diff.hex]
column-count = 4
column-size = 4

[diff.utf8]
column-count = 8
column-size = 4
